sudo: required
dist: xenial

language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -y build-essential fakeroot debhelper
  - sudo apt-get install -y libtool libtool-bin

script:
  # Build the package.
  - (cd pkg && make deb)
  # Run the unit and stress tests.
  - (cd src && make tests)
  - (cd src && make clean && make stress)
